SET SERVEROUTPUT ON
DECLARE

    CURSOR restCursor IS
        SELECT
            r.restaurant_id,
            r.name,
            r.location,
            r.halal_status,
            r.rating,
            NVL(SUM(od.quantity * od.unit_price), 0) AS total_revenue,
            NVL(SUM(od.quantity), 0) AS total_items_sold,
            COUNT(DISTINCT o.order_id) AS total_orders
        FROM RESTAURANT r
        LEFT JOIN CUST_ORDER o ON r.restaurant_id = o.restaurant_id
        LEFT JOIN ORDER_DETAILS od ON o.order_id = od.order_id
        GROUP BY r.restaurant_id, r.name, r.location, r.halal_status, r.rating
        ORDER BY total_revenue DESC;

    restRec      restCursor%ROWTYPE;
    v_rank       NUMBER := 0;
    v_grandRev   NUMBER(10,2) := 0;
    v_grandOrd   NUMBER := 0;

BEGIN

    DBMS_OUTPUT.PUT_LINE(LPAD('=', 110, '='));
    DBMS_OUTPUT.PUT_LINE(CHR(10));
    DBMS_OUTPUT.PUT_LINE('TOTAL REVENUE GENERATED BY EACH RESTAURANT');
    DBMS_OUTPUT.PUT_LINE(CHR(10));
    DBMS_OUTPUT.PUT_LINE(LPAD('=', 110, '='));

    -- COLUMN HEADING
    DBMS_OUTPUT.PUT_LINE(
        RPAD('RANK',   5,  ' ') || ' ' ||
        RPAD('ID',     5,  ' ') || ' ' ||
        RPAD('RESTAURANT',    25, ' ') || ' ' ||
        RPAD('LOCATION',      15, ' ') || ' ' ||
        RPAD('HALAL',         6,  ' ') || ' ' ||
        RPAD('RATING',        7,  ' ') || ' ' ||
        RPAD('ORDERS',        8,  ' ') || ' ' ||
        RPAD('ITEMS SOLD',    11, ' ') || ' ' ||
        RPAD('TOTAL REVENUE', 15, ' '));
    DBMS_OUTPUT.PUT_LINE(LPAD('-', 110, '-'));

    OPEN restCursor;

    LOOP
        FETCH restCursor INTO restRec;
        EXIT WHEN restCursor%NOTFOUND;

        v_rank     := v_rank + 1;
        v_grandRev := v_grandRev + restRec.total_revenue;
        v_grandOrd := v_grandOrd + restRec.total_orders;

        DBMS_OUTPUT.PUT_LINE(
            RPAD(v_rank,                  5,  ' ') || ' ' ||
            RPAD(restRec.restaurant_id,   5,  ' ') || ' ' ||
            RPAD(restRec.name,            25, ' ') || ' ' ||
            RPAD(restRec.location,        15, ' ') || ' ' ||
            RPAD(restRec.halal_status,    6,  ' ') || ' ' ||
            RPAD(TO_CHAR(restRec.rating, '9.9'), 7, ' ') || ' ' ||
            RPAD(restRec.total_orders,    8,  ' ') || ' ' ||
            RPAD(restRec.total_items_sold,11, ' ') || ' ' ||
            RPAD(TO_CHAR(restRec.total_revenue, '$999,999.99'), 15, ' '));

    END LOOP;

    CLOSE restCursor;

    -- FOOTER
    DBMS_OUTPUT.PUT_LINE(LPAD('-', 110, '-'));
    DBMS_OUTPUT.PUT_LINE('TOTAL RESTAURANTS: ' || v_rank || 
                         '   |   TOTAL ORDERS: ' || v_grandOrd || 
                         '   |   GRAND TOTAL REVENUE: ' || TO_CHAR(v_grandRev, '$999,999.99'));
    DBMS_OUTPUT.PUT_LINE(LPAD('=', 47, '=') || RPAD(' END OF REPORT ', 63, '='));

END;
/